spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(hGPWHd9HvMbB5TRqldwExY0P3XgARH50c0HPk7EGGZTHOu0vKS7td0m5IJquhjRc+lnDShy07fY=)
    username: ENC(9NJrqd6x0qYhCBP45BL6xQ==)
    password: ENC(pmp0DTDzTFMkZBfAX1zU3A==)

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: off

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ENC(hGPWHd9HvMbB5TRqldwExY0P3XgARH50c0HPk7EGGZTHOu0vKS7td0m5IJquhjRc+lnDShy07fY=)
    user: ENC(9NJrqd6x0qYhCBP45BL6xQ==)
    password: ENC(pmp0DTDzTFMkZBfAX1zU3A==)
