spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(jek7Ev6K/y6paYEaRvk4sEqXUx8FuOXtRVFWMhTWKApK0UfcNseDRA==)
    username: ENC(9NJrqd6x0qYhCBP45BL6xQ==)
    password: ENC(pmp0DTDzTFMkZBfAX1zU3A==)

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: off
